{
 "title": "Relay Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Relay Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "libp2p_relaysvc_status", "legendFormat": "active" }
   ]
  },
  { "title": "Reservations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Reservations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_relaysvc_reservations_total{type=\"opened\"} - ignoring(type) libp2p_relaysvc_reservations_total{type=\"closed\"}",
     "legendFormat": "active reservations"
    }
   ]
  },
  {
   "title": "Reservation Request Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "increase(libp2p_relaysvc_reservation_request_response_status_total[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Reservation Requests: New vs Renewal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(libp2p_relaysvc_reservations_total{type=\"opened\"}[$__rate_interval])",
     "legendFormat": "new"
    },
    {
     "expr": "increase(libp2p_relaysvc_reservations_total{type=\"renewed\"}[$__rate_interval])",
     "legendFormat": "renewed"
    }
   ]
  },
  {
   "title": "Reservation Request Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(libp2p_relaysvc_reservation_rejections_total[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total Data Transferred",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(libp2p_relaysvc_data_transferred_bytes_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_relaysvc_connections_total{type=\"opened\"} - ignoring(type) libp2p_relaysvc_connections_total{type=\"closed\"}",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Connection Request Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "increase(libp2p_relaysvc_connection_request_response_status_total[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bandwidth Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "2 * rate(libp2p_relaysvc_data_transferred_bytes_total[$__rate_interval])",
     "legendFormat": "bandwidth"
    }
   ]
  },
  {
   "title": "Connection Request Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "increase(libp2p_relaysvc_connection_rejections_total[$__rate_interval])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Connection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(libp2p_relaysvc_connection_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(libp2p_relaysvc_connection_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  }
 ]
}