{
 "title": "libp2p autonat",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Reachability Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_status",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Reachability status confidence",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autonat_reachability_status_confidnce",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client: DialResponse by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(libp2p_autonat_client_dialresponse_total[$__rate_interval])",
     "legendFormat": "{{response_status}}"
    }
   ]
  },
  {
   "title": "Server: Dial requests rate limited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "increase(libp2p_autonat_server_dialrefused_total[$__rate_interval])",
     "legendFormat": "{{refusal_reason}}"
    }
   ]
  },
  {
   "title": "server: DialResponse By Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "increase(libp2p_autonat_server_dialresponse_total[$__rate_interval])",
     "legendFormat": "{{response_status}}"
    }
   ]
  }
 ]
}