{
 "title": "libp2p Autorelay",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Scheduled Work", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Relay Finder Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "expr": "libp2p_autorelay_status", "legendFormat": "active" }
   ]
  },
  { "title": "Reservations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Current Reservations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_reservations_opened_total -  libp2p_autorelay_reservations_closed_total",
     "legendFormat": "current reservations"
    }
   ]
  },
  {
   "title": "Reservation Requests Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "increase(libp2p_autorelay_reservation_requests_outcome_total[$__rate_interval])",
     "legendFormat": "{{request_type}} reservation: {{outcome}}"
    }
   ]
  },
  { "title": "Candidates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Current Candidates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_candidates_total{type=\"added\"} - ignoring(type) libp2p_autorelay_candidates_total{type=\"removed\"}",
     "legendFormat": "num candidates"
    }
   ]
  },
  {
   "title": "Candidates Circuit V2 Support",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(libp2p_autorelay_candidates_circuit_v2_support_total[$__range])",
     "legendFormat": "{{support}}"
    }
   ]
  },
  {
   "title": "Next Old Candidate Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_scheduled_work_time{work_type=\"old candidate check\"} * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Relay Addresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Relay Addresses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_relay_addresses_count",
     "legendFormat": "num addresses"
    }
   ]
  },
  {
   "title": "Relay Addresses Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "increase(libp2p_autorelay_relay_addresses_updated_total[$__rate_interval])",
     "legendFormat": "update triggered"
    }
   ]
  }
 ]
}