{
 "title": "libp2p Identify",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pushes triggered",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(libp2p_identify_identify_pushes_triggered_total[$__rate_interval])",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "Identify Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_identify_identify_total[$__rate_interval])",
     "legendFormat": "{{dir}}"
    }
   ]
  },
  {
   "title": "Outgoing Address Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_identify_addrs_count", "legendFormat": "address count" }
   ]
  },
  {
   "title": "Outgoing Protocols Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_identify_protocols_count",
     "legendFormat": "protocols count"
    }
   ]
  },
  {
   "title": "Identify Push Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(libp2p_identify_identify_push_total[$__rate_interval])",
     "legendFormat": "{{dir}}"
    }
   ]
  },
  {
   "title": "Incoming Address Count (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum( rate(libp2p_identify_addrs_received_sum[$__rate_interval])) / sum( rate(libp2p_identify_addrs_received_count[$__rate_interval]))",
     "legendFormat": "address count"
    }
   ]
  },
  {
   "title": "Incoming Protocols Count (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate( libp2p_identify_protocols_received_sum[$__rate_interval])) / sum(rate(libp2p_identify_protocols_received_count[$__rate_interval]))",
     "legendFormat": "protocols count"
    }
   ]
  },
  {
   "title": "Peers: Push Support",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_identify_conn_push_support",
     "legendFormat": "{{support}}"
    }
   ]
  }
 ]
}