{
 "title": "libp2p EventBus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Events emitted By Subscriber",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_eventbus_subscriber_event_queued[$__rate_interval])",
     "legendFormat": "{{subscriber_name}}"
    }
   ]
  },
  {
   "title": "Events emitted by type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_eventbus_events_emitted_total[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Subscribers by event type",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_eventbus_subscribers_total",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Subscriber Queue Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "libp2p_eventbus_subscriber_queue_full",
     "legendFormat": "{{subscriber_name}}"
    }
   ]
  },
  {
   "title": "Subscriber Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(subscriber_name) (rate(libp2p_eventbus_subscriber_queue_length_sum[$__rate_interval])) / sum by(subscriber_name) (rate(libp2p_eventbus_subscriber_queue_length_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriber Queue Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(sum by (subscriber_name) (rate(libp2p_eventbus_subscriber_queue_length_sum[$__rate_interval])) / sum by(subscriber_name) (rate(libp2p_eventbus_subscriber_queue_length_count[$__rate_interval]))) / (sum by(subscriber_name) (rate(libp2p_eventbus_subscriber_event_queued[$__rate_interval])))",
     "legendFormat": "{{subscriber_name}}"
    }
   ]
  }
 ]
}